# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end

target 'sharescreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sharescreen

end

target 'sharescreenSetupUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sharescreenSetupUI

end
